#
# script that allows to generate resources.qrc file from the resources directory
# It also compiles it to src/ddt4all/generated/resources_rc.py
#
# from root project folder : python scripts/gen_qrc.py --compile
#
# Shamelessly generated by ChatGPT
#
from __future__ import annotations

import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class ResourceGroup:
    prefix: str     # ex: "/icons"
    root: Path      # ex: "resources/icons"


DEFAULT_EXTS = {".png", ".jpg", ".jpeg", ".svg", ".ico", ".qss", ".ui", ".ttf", ".otf"}


def iter_files(root: Path, exts: set[str]) -> list[Path]:
    files: list[Path] = []
    for p in root.rglob("*"):
        if p.is_file() and p.suffix.lower() in exts:
            files.append(p)
    return sorted(files)


def rel_posix(path: Path, base: Path) -> str:
    return path.resolve().relative_to(base.resolve()).as_posix()


def generate_qrc(
    *,
    project_root: Path,
    groups: list[ResourceGroup],
    output_qrc: Path,
    exts: set[str],
) -> None:
    output_qrc.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = []
    lines.append("<RCC>")

    for g in groups:
        group_root = (project_root / g.root).resolve()
        if not group_root.exists():
            print(f"[gen-qrc] Skip missing dir: {group_root}", file=sys.stderr)
            continue

        files = iter_files(group_root, exts)
        lines.append(f'  <qresource prefix="{g.prefix}">')

        for f in files:
            file_rel = rel_posix(f, project_root)   # chemin réel pour compilation
            alias = rel_posix(f, group_root)        # chemin exposé dans Qt (relatif au groupe)

            lines.append(f'    <file alias="{alias}">{file_rel}</file>')

        lines.append("  </qresource>")

    lines.append("</RCC>")
    output_qrc.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[gen-qrc] Wrote: {output_qrc}")


def compile_qrc(qrc_path: Path, output_py: Path) -> None:
    output_py.parent.mkdir(parents=True, exist_ok=True)
    cmd = ["pyrcc5", str(qrc_path), "-o", str(output_py)]
    print("[gen-qrc] Compile:", " ".join(cmd))
    subprocess.check_call(cmd)
    print(f"[gen-qrc] Wrote: {output_py}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate Qt .qrc from resource directories (preserve subdirs, no flatten)."
    )
    parser.add_argument("--project-root", default=".", help="Project root (default: current directory).")
    parser.add_argument("--out-qrc", default="resources.qrc", help="Output .qrc path relative to project root.")
    parser.add_argument("--compile", action="store_true", help="Also compile to a Python module using pyrcc5.")
    parser.add_argument(
        "--out-py",
        default="src/ddt4all/generated/resources_rc.py",
        help="Output python module for compiled resources.",
    )
    parser.add_argument("--ext", action="append", default=[], help="Extra extension to include (repeatable).")

    args = parser.parse_args(argv)

    project_root = Path(args.project_root).resolve()
    out_qrc = (project_root / args.out_qrc).resolve()
    out_py = (project_root / args.out_py).resolve()

    exts = set(DEFAULT_EXTS)
    for e in args.ext:
        exts.add(e if e.startswith(".") else f".{e}")

    groups = [
        ResourceGroup(prefix="/icons", root=Path("resources/icons")),
        ResourceGroup(prefix="/styles", root=Path("resources/styles")),
    ]

    generate_qrc(project_root=project_root, groups=groups, output_qrc=out_qrc, exts=exts)

    if args.compile:
        compile_qrc(out_qrc, out_py)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())