#!/usr/bin/env python3
# shamelessely generated by ChatGPT
"""
i18n.py — replace pot_create.bat / po_merge.bat / po_to_mo.bat / po2mo.bat

Usage examples:
  python i18n.py pot-create
  python i18n.py po-merge
  python i18n.py po-to-mo
  python i18n.py po2mo
  python i18n.py full-gen
  python i18n.py full-gen --dry-run -v
"""

from pathlib import Path
import argparse
import shutil
import subprocess
import sys
import os
import tempfile
import fnmatch

# Defaults
DEFAULT_DOMAIN = "ddt4all"
DEFAULT_LOCALEDIR = "locales"
DEFAULT_SCAN_ROOT = "src"
DEFAULT_GENERATEDDIR = "src/ddt4all/generated/locales"
DEFAULT_EXCLUDES = [
    ".git", "venv", "env", "build", "dist", "__pycache__", ".tox", ".eggs", "generated"
]
WIN_CMD_LIMIT = 8000

# ---- Helpers ----
def which_or_fail(cmd):
    path = shutil.which(cmd)
    if not path:
        raise RuntimeError(f"La commande requise '{cmd}' n'est pas trouvée dans le PATH. Installe gettext/tools.")
    return path

def run(cmd, dry_run=False, verbose=False, capture_output=False):
    if dry_run or verbose:
        print("RUN:", " ".join(cmd))
    if dry_run:
        return 0
    if capture_output:
        return subprocess.run(cmd, check=False, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    return subprocess.run(cmd, check=False)

def gather_pyfiles(root: Path, excludes, include_patterns=None):
    include_patterns = include_patterns or ["*.py"]
    pyfiles = []
    for p in root.rglob("*.py"):
        s = str(p)
        skip = False
        for ex in excludes:
            if ex and (ex in s or fnmatch.fnmatch(s, ex)):
                skip = True
                break
        if skip:
            continue
        matched = any(fnmatch.fnmatch(p.name, pat) for pat in include_patterns)
        if matched:
            pyfiles.append(p.resolve())
    return sorted(pyfiles)

def make_temp_file_with_lines(lines):
    tf = tempfile.NamedTemporaryFile(delete=False, mode="w", encoding="utf-8", newline="\n")
    for l in lines:
        tf.write(str(l))
        tf.write("\n")
    tf.close()
    return Path(tf.name)

def ensure_dir(p: Path, dry_run=False, verbose=False):
    if dry_run or verbose:
        print("MKDIR:", str(p))
    if not dry_run:
        p.mkdir(parents=True, exist_ok=True)

# ---- Commands ----
def pot_create(args):
    xgettext = which_or_fail("xgettext")
    root = Path(args.root).resolve()
    localedir = Path(args.localedir).resolve()
    domain = args.domain
    excludes = args.exclude or []
    excludes = list(set(excludes + DEFAULT_EXCLUDES))
    pyfiles = gather_pyfiles(root, excludes)
    if not pyfiles:
        print("[WARN] Aucun fichier .py trouvé.")
        return 1

    ensure_dir(localedir, dry_run=args.dry_run, verbose=args.verbose)
    pot_path = localedir / f"{domain}.pot"

    xgettext_base = [
        xgettext,
        "--from-code=UTF-8",
        "--no-location",
        f"--width={args.width}",
        "--no-wrap",
        "-o", str(pot_path)
    ]

    joined = " ".join(str(p) for p in pyfiles)
    if os.name == "nt" and len(joined) > WIN_CMD_LIMIT:
        filelist = make_temp_file_with_lines(pyfiles)
        cmd = [*xgettext_base, "-f", str(filelist)]
        if args.verbose:
            print("[INFO] utilisation d'un fichier temporaire pour xgettext:", filelist)
        res = run([str(c) for c in cmd], dry_run=args.dry_run, verbose=args.verbose)
        if not args.dry_run:
            try:
                filelist.unlink()
            except Exception:
                pass
    else:
        cmd = [*xgettext_base, *[str(p) for p in pyfiles]]
        res = run([str(c) for c in cmd], dry_run=args.dry_run, verbose=args.verbose)

    if isinstance(res, subprocess.CompletedProcess) and res.returncode != 0 or res == 1:
        print("[ERR] xgettext a échoué.")
        return 2
    print(f"[OK] {pot_path} généré ({len(pyfiles)} fichiers analysés)")
    return 0

def po_merge(args):
    msgmerge = which_or_fail("msgmerge")
    msgattrib = which_or_fail("msgattrib")
    msgfmt = which_or_fail("msgfmt")
    localedir = Path(args.localedir).resolve()
    domain = args.domain
    pot_path = Path(args.pot).resolve() if args.pot else (localedir / f"{domain}.pot")
    if not pot_path.exists():
        print(f"[ERR] .pot introuvable : {pot_path}")
        return 3

    langs = [p.name for p in localedir.iterdir() if p.is_dir()]
    if not langs:
        print("[WARN] Aucune langue trouvée dans", localedir)
        return 0

    for lang in sorted(langs):
        po = localedir / lang / "LC_MESSAGES" / f"{domain}.po"
        if not po.exists():
            print(f"[SKIP] {po} introuvable")
            continue

        cmd_merge = [msgmerge, "--update", str(po), str(pot_path)]
        run(cmd_merge, dry_run=args.dry_run, verbose=args.verbose)

        tmp = po.with_suffix(".tmp.po")
        cmd_attr = [msgattrib, "--no-obsolete", "-o", str(tmp), str(po)]
        rc = run(cmd_attr, dry_run=args.dry_run, verbose=args.verbose)

        ok = args.dry_run or (
            (not isinstance(rc, int) and getattr(rc, "returncode", 0) == 0)
            or (isinstance(rc, int) and rc == 0)
        )
        if ok and not args.dry_run:
            try:
                tmp.replace(po)
            except Exception:
                tmp_text = tmp.read_text(encoding="utf-8") if tmp.exists() else None
                if tmp_text is not None:
                    po.write_text(tmp_text, encoding="utf-8")
                    try:
                        tmp.unlink()
                    except Exception:
                        pass

        cmd_stats = [msgfmt, "--statistics", "-c", "-o", os.devnull, str(po)]
        run(cmd_stats, dry_run=args.dry_run, verbose=args.verbose)
        print(f"[OK] {po} mis à jour")

    return 0

def po_to_mo(args):
    """
    Compile les .po en .mo uniquement dans generated/<lang>/LC_MESSAGES/<domain>.mo
    (PAS de .mo à côté des .po)
    """
    msgfmt = which_or_fail("msgfmt")
    localedir = Path(args.localedir).resolve()
    domain = args.domain
    generated_root = Path(args.generated_dir).resolve()

    langs = [p.name for p in localedir.iterdir() if p.is_dir()]
    if not langs:
        print("[WARN] Aucune langue trouvée dans", localedir)
        return 0

    for lang in sorted(langs):
        po = localedir / lang / "LC_MESSAGES" / f"{domain}.po"
        if not po.exists():
            print(f"[SKIP] {po} introuvable")
            continue

        target_mo = generated_root / lang / "LC_MESSAGES" / f"{domain}.mo"
        ensure_dir(target_mo.parent, dry_run=args.dry_run, verbose=args.verbose)

        cmd = [msgfmt, str(po), "-o", str(target_mo)]
        rc = run(cmd, dry_run=args.dry_run, verbose=args.verbose)

        success = args.dry_run or (
            (not isinstance(rc, int) and getattr(rc, "returncode", 0) == 0)
            or (isinstance(rc, int) and rc == 0)
        )
        if success:
            print(f"[OK] {target_mo} généré")
        else:
            print(f"[ERR] échec compilation {po}")

    return 0

def full_gen(args):
    """
    Enchaîne toutes les étapes nécessaires pour générer les .mo dans generated:
      1) pot-create
      2) po-merge
      3) po-to-mo (vers generated)
    """
    r1 = pot_create(argparse.Namespace(
        root=args.root,
        localedir=args.localedir,
        domain=args.domain,
        exclude=args.exclude or [],
        width=args.width,
        dry_run=args.dry_run,
        verbose=args.verbose
    ))
    if r1 != 0:
        return r1

    r2 = po_merge(argparse.Namespace(
        localedir=args.localedir,
        domain=args.domain,
        pot=args.pot,
        dry_run=args.dry_run,
        verbose=args.verbose
    ))
    if r2 != 0:
        return r2

    r3 = po_to_mo(argparse.Namespace(
        localedir=args.localedir,
        domain=args.domain,
        generated_dir=args.generated_dir,
        dry_run=args.dry_run,
        verbose=args.verbose
    ))
    return r3

# ---- CLI ----
def main():
    parser = argparse.ArgumentParser(description="i18n helper (pot-create, po-merge, po-to-mo) + full-gen")
    sub = parser.add_subparsers(dest="cmd", required=True)

    common = argparse.ArgumentParser(add_help=False)
    common.add_argument("-d", "--localedir", default=DEFAULT_LOCALEDIR, help="répertoire des locales (default: locale)")
    common.add_argument("--domain", default=DEFAULT_DOMAIN, help=f"gettext domain (default: {DEFAULT_DOMAIN})")
    common.add_argument("--generated-dir", default=DEFAULT_GENERATEDDIR,
                        help=f"répertoire cible des .mo (default: {DEFAULT_GENERATEDDIR})")
    common.add_argument("--dry-run", action="store_true", help="ne rien exécuter; juste afficher les commandes")
    common.add_argument("-v", "--verbose", action="store_true", help="mode verbeux")

    p1 = sub.add_parser("pot-create", parents=[common], help="génère <localedir>/<domain>.pot à partir des .py")
    p1.add_argument("--root", default=DEFAULT_SCAN_ROOT, help="racine pour le scan des .py (def: src)")
    p1.add_argument("--exclude", action="append", help="pattern ou sous-chemin à exclure (répéter pour plusieurs)")
    p1.add_argument("--width", default=400, type=int, help="width option pour xgettext (default 400)")

    p2 = sub.add_parser("po-merge", parents=[common], help="merge .pot -> .po (msgmerge + msgattrib)")
    p2.add_argument("--pot", help="chemin vers .pot (si omis: <localedir>/<domain>.pot)")

    p3 = sub.add_parser("po-to-mo", parents=[common], help="compile tous les .po en .mo (dans generated uniquement)")
    p4 = sub.add_parser("po2mo", parents=[common], help="alias pour po-to-mo")

    p5 = sub.add_parser("full-gen", parents=[common], help="pot-create + po-merge + po-to-mo (dans generated)")
    p5.add_argument("--root", default=DEFAULT_SCAN_ROOT, help="racine pour le scan des .py (def: src)")
    p5.add_argument("--exclude", action="append", help="pattern ou sous-chemin à exclure (répéter pour plusieurs)")
    p5.add_argument("--width", default=400, type=int, help="width option pour xgettext (default 400)")
    p5.add_argument("--pot", help="chemin vers .pot (si omis: <localedir>/<domain>.pot)")

    args = parser.parse_args()
    try:
        if args.cmd == "pot-create":
            sys.exit(pot_create(args) or 0)
        elif args.cmd == "po-merge":
            sys.exit(po_merge(args) or 0)
        elif args.cmd in ("po-to-mo", "po2mo"):
            sys.exit(po_to_mo(args) or 0)
        elif args.cmd == "full-gen":
            sys.exit(full_gen(args) or 0)
        else:
            parser.print_help()
            sys.exit(1)
    except RuntimeError as e:
        print("[ERREUR]", e)
        sys.exit(5)

if __name__ == "__main__":
    main()